name: github-pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "10 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: install dependencies
        run: npm ci

      - name: update data.json
        run: npm run update-data
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}

      - name: build
        run: npm run build
        env:
          NITRO_PRESET: github_pages

      - name: configure pages
        uses: actions/configure-pages@v3

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./.output/public

      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v2
